title: 聖潔記事本
description: No
permalink: /:title/

markdown: redcarpet
  redcarpet:
    extensions:
      - hard_wrap
      - no_intra_emphasis
      - autolink
      - strikethrough
      - fenced_code_blocks
      - with_toc_data
      - tables
      - underline